export const BUDGETING_KB = `
BUDGETING KNOWLEDGE BASE

50/30/20 Rule: The most popular budgeting framework divides your take-home income into three buckets. 50 percent goes to needs - rent, groceries, utilities, insurance premiums, loan EMIs, and transportation. 30 percent goes to wants - dining out, entertainment, subscriptions, shopping, and vacations. 20 percent goes to savings and investments - SIPs, PPF, emergency fund, and debt repayment beyond minimums. For example, on a ₹60,000 take-home salary: ₹30,000 for needs, ₹18,000 for wants, and ₹12,000 for savings. As your income grows, try shifting to 40/20/40 by keeping wants flat and increasing the savings portion.

Zero-Based Budgeting: Every rupee of income is assigned a purpose before the month begins, so income minus expenses equals zero. Start by listing all fixed expenses (rent, EMIs, insurance), then variable necessities (groceries, fuel), then savings goals (SIPs, RDs), and finally discretionary spending. The key difference from the 50/30/20 rule is that you plan exact amounts for each category rather than broad percentages. This method works exceptionally well for irregular income earners like freelancers - budget based on your minimum expected income and allocate windfalls separately.

Envelope Method: A cash-based system where you withdraw your monthly budget in cash and divide it into labeled envelopes - groceries ₹8,000, transport ₹3,000, entertainment ₹5,000, and so on. When an envelope is empty, you stop spending in that category. The digital version uses separate bank accounts or apps like Walnut or YNAB. This method is highly effective for controlling overspending because physical cash creates a tangible sense of loss that UPI and card payments do not.

Reverse Budgeting (Pay Yourself First): Instead of budgeting expenses and saving what remains, you save first and spend the rest freely. On salary day, auto-debit your target savings - SIPs, RDs, PPF contributions - and then spend the remainder without guilt or tracking. If your take-home is ₹80,000 and your savings target is ₹25,000, auto-invest ₹25,000 on the 2nd of every month and live on the remaining ₹55,000. This is the simplest budgeting method and works well for people who dislike detailed tracking.

Tracking Expenses: You cannot manage what you do not measure. Track every expense for at least 3 months to understand your actual spending patterns. Use UPI transaction history, bank statements, or apps to categorize spending. Most people discover 10 to 15 percent of their income goes to unplanned or forgotten expenses. Common leaks in Indian households include multiple OTT subscriptions (₹500-2,000/month), food delivery apps (₹3,000-8,000/month), and unused gym or club memberships.

Budget Review Cycles: Review your budget weekly for the first 3 months to build the habit, then shift to monthly reviews. Conduct a major review quarterly to adjust for salary changes, new goals, or lifestyle shifts. Annual reviews should coincide with tax planning in January-March. Key questions during review: Did I hit my savings target? Which categories consistently overshoot? Are there new expenses I need to plan for? Adjust categories by 5 to 10 percent each cycle rather than making dramatic changes that are hard to sustain.

Budgeting for Irregular Income: Freelancers, business owners, and commission-based earners should budget based on their lowest earning month from the past 12 months. In high-earning months, build a buffer fund equal to 2 months of expenses. Use the surplus to prepay annual expenses, boost investments, or accelerate debt repayment. Keep business and personal finances strictly separate with different bank accounts.
`;
