export const DEBT_MANAGEMENT_KB = `
DEBT MANAGEMENT KNOWLEDGE BASE

Debt Avalanche vs Snowball Method: The avalanche method prioritizes paying off debt with the highest interest rate first, minimizing total interest paid. The snowball method pays off the smallest balance first for quick psychological wins. Example: if you have a credit card at 42 percent (₹30,000), a personal loan at 14 percent (₹2,00,000), and a car loan at 9 percent (₹5,00,000), the avalanche method tackles the credit card first, then personal loan, then car loan. The snowball method also starts with the credit card (smallest balance) but then switches to the personal loan. Mathematically, avalanche saves more money, but snowball has higher completion rates because the motivation from early wins keeps people going.

Debt-to-Income (DTI) Ratio: Your total monthly debt payments divided by gross monthly income. A DTI below 30 percent is healthy, 30 to 40 percent is manageable but needs attention, and above 40 percent is a red flag. For example, if your gross monthly income is ₹1,00,000 and total EMIs (home loan, car loan, credit card minimums) are ₹35,000, your DTI is 35 percent. Banks typically reject new loans when DTI exceeds 50 percent. Aim to keep your DTI below 30 percent by either increasing income or reducing debt commitments.

Good Debt vs Bad Debt: Good debt finances appreciating assets or income generation - a home loan (property appreciation plus tax benefits under Section 24 and 80C), education loan (higher earning potential, Section 80E deduction), or a business loan for a profitable venture. Bad debt finances depreciating assets or consumption - credit card debt at 36 to 42 percent, personal loans for vacations or weddings, car loans for expensive vehicles beyond your means. Rule of thumb: if the asset financed will be worth less in 5 years, it is bad debt.

Credit Card Management: Always pay the full outstanding balance by the due date. Paying only the minimum (typically 5 percent of outstanding) triggers interest on the entire outstanding from the date of each transaction at 36 to 42 percent per annum. A ₹1,00,000 credit card balance paid in minimums takes over 8 years to clear and costs ₹1,60,000 in interest alone. Use credit cards for the rewards and interest-free period, but treat them as debit cards mentally. If you cannot control credit card spending, switch to a debit card or UPI.

Loan Prepayment Strategy: For floating rate home loans, even small prepayments dramatically reduce tenure and total interest. Prepaying ₹1,00,000 on a ₹50L home loan at 8.5 percent in the early years can save ₹2.5L to ₹3L in total interest. Prioritize prepaying loans by interest rate - credit cards first, then personal loans, then car loans, then home loans. Note that prepayment of floating rate home loans and education loans carries zero penalty by RBI regulation. Fixed rate loans may have prepayment charges of 2 to 4 percent.

EMI Management: Total EMIs should not exceed 40 percent of net take-home pay. Before taking a new loan, calculate the EMI using the formula or an online calculator and assess its impact on your budget. For home loans, the EMI should ideally be below 30 percent of take-home salary. Choose tenure wisely - a longer tenure reduces EMI but massively increases total interest. A ₹50L home loan at 8.5 percent for 20 years has an EMI of ₹43,391 with total interest of ₹54.1L, while the same loan for 30 years has an EMI of ₹38,446 but total interest of ₹88.4L.

Debt Consolidation: If you have multiple high-interest debts (credit cards, personal loans), consider consolidating them into a single lower-interest loan. A personal loan at 12 to 14 percent to clear credit card debt at 40 percent saves significant interest. Balance transfer offers between credit cards can provide 0 percent interest for 3 to 6 months. However, consolidation only works if you stop accumulating new debt simultaneously. Cut up the cleared credit cards if needed.

When to Borrow: Borrow only when the expected return exceeds the cost of borrowing. A home loan at 8.5 percent for a property in a growing area appreciating at 10 to 12 percent can make sense. An education loan at 9 percent leading to a salary jump of 50 percent or more is worth it. Never borrow for consumption or to maintain a lifestyle beyond your means. Before any loan, ask: can I afford the EMI comfortably and will this asset generate value greater than the interest I will pay?
`;
