export const FINANCIAL_RATIOS_KB = `
FINANCIAL RATIOS KNOWLEDGE BASE

Savings Rate: The percentage of take-home income that you save and invest each month. Formula: (income minus expenses) divided by income times 100. A healthy savings rate is 20 percent or higher. Aspirational target is 30 to 50 percent for accelerated wealth building. FIRE aspirants aim for 50 to 70 percent. If your take-home is ₹80,000 and you save ₹20,000, your savings rate is 25 percent. Track this monthly. A savings rate below 10 percent signals a spending problem or income insufficiency that needs immediate attention.

Debt-to-Income (DTI) Ratio: Total monthly debt payments (EMIs, credit card minimums, loan installments) divided by gross monthly income. Under 20 percent is excellent and allows room for new loans. 20 to 30 percent is manageable. 30 to 40 percent is concerning - avoid new debt. Above 40 percent is a debt crisis requiring urgent action. Example: ₹90,000 gross income with ₹25,000 in EMIs gives a DTI of 27.8 percent. Banks use this ratio to assess loan eligibility - most reject applications when DTI exceeds 50 percent.

Net Worth Tracking: Net worth equals total assets minus total liabilities. Assets include investments (mutual funds, stocks, FDs, PPF, EPF, NPS), property (current market value), gold, and cash. Liabilities include outstanding home loan, car loan, personal loan, credit card dues, and any other debts. Track net worth quarterly. A positive and growing net worth indicates financial progress. Example: if your assets total ₹45L and liabilities are ₹30L (home loan), your net worth is ₹15L. A 25-year-old with zero net worth is fine; a 40-year-old with zero net worth needs urgent course correction.

Expense Ratio: In investing, the expense ratio is the annual fee charged by a mutual fund as a percentage of assets under management. Index funds charge 0.1 to 0.3 percent, direct plans of active funds charge 0.5 to 1.5 percent, and regular plans charge 1.5 to 2.5 percent. The difference may seem small, but over 25 years, a 1 percent higher expense ratio can reduce your final corpus by 15 to 20 percent. Always invest through direct plans via platforms like Kuvera, Groww, or AMC websites. Never invest through regular plans pushed by distributors unless they provide significant advisory value.

Investment Return Benchmarks: Use these as reality checks. Savings account: 3 to 4 percent. Fixed deposits: 6.5 to 7.5 percent. PPF: 7.1 percent. EPF: 8.25 percent. Debt mutual funds: 7 to 9 percent. Balanced/hybrid funds: 9 to 11 percent. Large-cap equity: 10 to 13 percent. Mid-cap equity: 12 to 15 percent. Small-cap equity: 14 to 18 percent (with much higher volatility). Gold: 8 to 10 percent long-term. Inflation: 6 to 7 percent. Any scheme promising guaranteed returns above 12 percent is likely fraudulent. Real returns (after inflation) are what matter - FDs often deliver near-zero real returns.

Financial Independence Ratio: Your passive income (from investments, rental income, interest, dividends) divided by your monthly expenses. When this ratio reaches 1.0 (100 percent), you are financially independent - you can cover all expenses without active employment. At 0.5, you are halfway there. Track this annually. Example: if monthly expenses are ₹60,000 and investment income (SWP, dividends, rent) generates ₹24,000/month, your FI ratio is 0.4 or 40 percent. The goal is to grow this ratio steadily toward 1.0 by increasing investment corpus and managing expense growth.

Liquid Net Worth: Net worth minus illiquid assets (primary residence, locked-in EPF/PPF, restricted stock). This tells you how much you could actually access in an emergency. Many Indians have high net worth on paper (due to property) but low liquid net worth. If your net worth is ₹1 crore but ₹70L is your home and ₹15L is locked in EPF/PPF, your liquid net worth is only ₹15L. Aim for liquid net worth equal to at least 12 months of expenses as a financial stability metric beyond just the emergency fund.

Wealth-to-Income Ratio: Your net worth divided by your annual gross income. A useful benchmark by age: at 30, aim for 1x annual income. At 35, aim for 2x. At 40, aim for 4x. At 45, aim for 7x. At 50, aim for 10x. At 55, aim for 15x. At 60, aim for 20x or more. For example, a 40-year-old earning ₹15L per year should target a net worth of approximately ₹60L. Falling significantly behind these benchmarks suggests insufficient savings rate or poor investment choices. Use this ratio as a periodic health check.
`;
