export const INDIAN_INSTRUMENTS_KB = `
INDIAN FINANCIAL INSTRUMENTS KNOWLEDGE BASE

Public Provident Fund (PPF): Government-backed, EEE (exempt-exempt-exempt) status making it fully tax-free. Current interest rate is 7.1 percent, compounded annually, revised quarterly by the government. Minimum annual deposit ₹500, maximum ₹1,50,000. Lock-in period of 15 years, extendable in 5-year blocks. Partial withdrawals allowed from year 7 (up to 50 percent of balance at end of year 4). Loans available from year 3 to year 6. One of the safest instruments for the debt portion of a long-term portfolio. Best opened at a bank for easier online management rather than at the post office.

Employee Provident Fund (EPF): Mandatory for salaried employees in establishments with 20 or more workers. Employee contributes 12 percent of basic salary, employer contributes 12 percent - of which 3.67 percent goes to EPF and 8.33 percent to EPS (Employee Pension Scheme, capped at ₹15,000 basic). Current interest rate is 8.25 percent. Tax-free if withdrawn after 5 years of continuous service. Can be withdrawn for home purchase, medical emergency, or education (partial withdrawal conditions apply). Always transfer EPF when changing jobs via the EPFO Unified Portal - never withdraw prematurely.

National Pension System (NPS): Two tiers - Tier 1 is a retirement account with tax benefits and lock-in until age 60; Tier 2 is a voluntary savings account with no tax benefit and full liquidity. Tier 1 asset classes: Equity (E, up to 75 percent for Active Choice), Corporate Bonds (C), and Government Securities (G). Auto Choice (Lifecycle Fund) automatically reduces equity allocation as you age. At 60, withdraw up to 60 percent as tax-free lump sum, and minimum 40 percent must buy an annuity. Partial withdrawal of 25 percent allowed after 3 years for specified purposes (education, medical, home purchase). Additional ₹50,000 tax deduction under 80CCD(1B).

Sukanya Samriddhi Yojana (SSY): For the girl child, opened by parents or guardians. Eligibility: girl child under 10 years, maximum 2 accounts (one per girl child). Current interest rate is 8.2 percent. Minimum deposit ₹250/year, maximum ₹1,50,000/year. Matures 21 years from opening or on the girl's marriage after age 18. Partial withdrawal of 50 percent allowed after the girl turns 18 for education. Qualifies under Section 80C with EEE status. One of the highest-yielding government small savings schemes - excellent for planning a daughter's education or marriage.

Senior Citizens Savings Scheme (SCSS): For individuals aged 60 and above (55 for retired defence/government employees). Current interest rate is 8.2 percent, paid quarterly. Maximum investment ₹30 lakh per individual. Tenure of 5 years, extendable by 3 years. Premature withdrawal allowed after 1 year with penalty. Qualifies under Section 80C. TDS is deducted if annual interest exceeds ₹50,000. Ideal for retirees seeking regular quarterly income with sovereign safety.

Sovereign Gold Bonds (SGB): Issued by RBI on behalf of the government, denominated in grams of gold. You earn 2.5 percent annual interest (paid semi-annually) on top of gold price appreciation. Tenure is 8 years with exit option from year 5. Capital gains are fully tax-free if held to maturity. No storage cost or purity risk unlike physical gold. Minimum investment is 1 gram, maximum 4 kg per individual per year. SGBs are the most tax-efficient way to invest in gold in India. Available during RBI issuance windows or on stock exchanges at market price.

Kisan Vikas Patra (KVP) and National Savings Certificate (NSC): KVP currently doubles your investment in approximately 115 months (roughly 9.5 years) at 7.5 percent interest. No upper limit on investment. Available at post offices and select banks. NSC offers 7.7 percent compounded annually with a 5-year lock-in. Maximum investment has no cap. NSC interest is deemed reinvested and qualifies under 80C each year (except the final year). Both are low-risk instruments suitable for conservative investors who prefer guaranteed returns.

Recurring Deposits (RD): Monthly fixed deposits available at banks and post offices. Bank RDs offer 6.5 to 7.5 percent for most tenures. Post office RD offers 6.7 percent for 5 years. Interest is taxable at slab rate. Premature closure allowed after 3 years (post office) or as per bank rules. RDs are suitable for short-term goals (1-3 years) where you want guaranteed returns and capital safety. For longer time horizons, SIPs in debt or hybrid funds typically offer better post-tax returns.

Post Office Schemes Overview: The post office offers a comprehensive suite of small savings: savings account (4 percent), 1/2/3/5 year time deposits (6.9-7.5 percent), Monthly Income Scheme or MIS (7.4 percent, monthly payout, 5-year tenure, max ₹9L individual/₹15L joint), and the above-mentioned PPF, SSY, SCSS, NSC, KVP, and RD. Post office schemes carry sovereign guarantee and are ideal for conservative investors. Interest rates are reviewed quarterly by the government. Most schemes now available with online access through India Post Payments Bank.
`;
