export const INVESTMENT_KB = `
INVESTMENT KNOWLEDGE BASE

Compound Interest and the Rule of 72: Compound interest is the single most powerful force in wealth building - you earn returns on your returns. The Rule of 72 provides a quick mental shortcut: divide 72 by the annual return rate to estimate how many years it takes to double your money. At 12 percent returns (typical equity), your money doubles every 6 years. At 7 percent (FD or PPF), it doubles every ~10.3 years. At 15 percent, it doubles in under 5 years. This makes the return rate and time horizon the two most critical variables in investing.

SIP and Dollar Cost Averaging: A Systematic Investment Plan invests a fixed amount monthly into a mutual fund regardless of market conditions. When prices are high, you buy fewer units; when prices are low, you buy more units. Over time, this averages your purchase cost and removes the need to time the market. For example, a ₹10,000 monthly SIP in a Nifty 50 index fund ensures disciplined investing. SIP works best over long periods of 7 years or more where market cycles smooth out.

Asset Allocation: A foundational rule is to hold (100 minus your age) percent in equity and the rest in debt instruments. A 30-year-old would target 70 percent equity and 30 percent debt. A 50-year-old would shift to 50 percent equity and 50 percent debt. This is a starting guideline - your actual allocation should also consider risk tolerance, income stability, and goal timelines. Aggressive investors with stable government jobs might hold more equity; conservative investors or those nearing a goal should hold more debt.

Risk-Return Tradeoff: Higher returns always come with higher risk and volatility. Fixed deposits offer roughly 7 percent with near-zero risk but barely beat inflation. Equity mutual funds have historically delivered 12 to 15 percent but can drop 30 to 40 percent in a bad year. Debt mutual funds offer 7 to 9 percent with moderate risk. Gold delivers 8 to 10 percent long-term with moderate volatility. Understanding this tradeoff prevents panic selling during downturns and unrealistic return expectations.

Index Investing: A Nifty 50 index fund with an expense ratio of 0.1 to 0.2 percent is the simplest and most effective equity investment for most people. Data consistently shows that over a 10-year period, index funds beat 80 to 90 percent of actively managed funds after fees. Popular options include UTI Nifty 50 Index Fund and HDFC Index Fund Nifty 50 Plan. For broader exposure, consider a Nifty Next 50 or Nifty 500 index fund. Avoid paying 1.5 to 2 percent expense ratios for active funds unless you have strong conviction.

Diversification: Spread investments across asset classes to reduce overall portfolio risk. A well-diversified Indian portfolio might include domestic equity (large, mid, small cap), debt (PPF, debt funds, FDs), gold (Sovereign Gold Bonds or Gold ETFs), and international equity (US index fund like Motilal Oswal S&P 500). No single asset class wins every year. Diversification ensures that poor performance in one area is offset by gains in another.

Lump Sum vs SIP: Academic research shows that investing a lump sum immediately beats SIP roughly two-thirds of the time because markets trend upward over long periods. However, SIP significantly reduces behavioral risk - the fear and regret of investing a large amount right before a crash. For amounts under ₹5L, lump sum is generally fine. For larger amounts, consider a Systematic Transfer Plan to manage anxiety while deploying capital within 3 to 6 months.

Power of Starting Early: Time is the most valuable asset in investing. Investing ₹5,000 per month starting at age 25 at 12 percent annual returns grows to approximately ₹3.25 crore by age 60. The same ₹5,000 per month starting at age 35 reaches only about ₹95 lakh by age 60. The 10-year head start results in more than 3 times the final amount, even though the difference in total invested is only ₹6 lakh. This dramatic gap is entirely due to compound interest having more time to work. Starting early, even with small amounts, is far more impactful than starting late with large amounts.

Rebalancing: Over time, market movements will drift your portfolio away from your target asset allocation. If equity rallies, you may end up with 80 percent equity instead of your target 70 percent. Rebalancing means selling some equity and buying debt to return to the target. Do this annually or when any asset class drifts more than 5 percentage points from the target. Rebalancing enforces the discipline of buying low and selling high.

Systematic Transfer Plan (STP): When you receive a lump sum such as a bonus, inheritance, or property sale proceeds, park it in a liquid or ultra-short-term debt fund and set up a weekly or monthly STP into your target equity fund over 3 to 6 months. This gives you the safety of gradual deployment while keeping your money productive in the liquid fund at roughly 6 to 7 percent instead of sitting idle in a savings account at 3 to 4 percent.
`;
