export const LIFE_STAGES_KB = `
LIFE STAGES FINANCIAL PLANNING KNOWLEDGE BASE

Student Phase (Age 16-22): Build money habits before earning begins. Open a savings account and learn basic budgeting. If receiving pocket money or stipend, practice the 50/30/20 rule even with ₹2,000 to ₹5,000 per month. Start reading about personal finance - books like Let's Talk Money by Monika Halan or The Psychology of Money by Morgan Housel. Avoid lifestyle debt and credit cards. If earning through internships or freelancing, start a ₹500/month SIP in an index fund - the habit matters more than the amount. Understand the power of compounding early.

First Job (Age 22-25): This is the most critical phase for establishing financial foundations. Priority 1: build an emergency fund of 3 months' expenses in a liquid fund or savings account (target ₹1L to ₹2L). Priority 2: buy a term life insurance plan of ₹50L to ₹1 crore if anyone depends on your income, and a health insurance plan of ₹5L to ₹10L. Priority 3: start a SIP of at least 20 percent of take-home salary in an index fund. Avoid lifestyle inflation - live as if you still earn a student stipend for the first 2 years. This period sets the trajectory for your entire financial life. Skip the new car and expensive gadgets.

Late 20s (Age 25-30): Increase SIP amounts with every salary hike - commit at least 50 percent of each raise to investments. Start planning for a home - if buying in 3 to 5 years, begin saving the down payment in a balanced hybrid fund or recurring deposit. Total investment allocation should be 80 percent equity, 20 percent debt. Target net worth of 1x annual income by age 30. Max out Section 80C (₹1.5L in ELSS/PPF) and 80CCD(1B) (₹50K in NPS). Build professional skills aggressively - the biggest asset at this age is your earning potential. Start an emergency fund top-up to 6 months of expenses.

30s - Building Phase (Age 30-40): Likely married with growing responsibilities. Review and increase insurance - term cover should be 10 to 15x family income, health cover should be ₹15L to ₹25L with super top-up. If planning children, start a dedicated SIP for education fund - ₹10,000/month at 12 percent for 18 years grows to ₹75L. Write a will and assign nominees on all accounts and policies. Home loan EMI should not exceed 30 percent of take-home pay. Shift allocation to 70 percent equity, 20 percent debt, 10 percent gold. Target net worth of 2 to 4x annual income by end of this decade.

40s - Acceleration Phase (Age 40-50): Peak earning years - aggressively save 30 to 40 percent of income. Children's education fund should be substantially built. Start dedicated college fund if not already running - engineering/medical education costs ₹15L to ₹40L, foreign education ₹50L to ₹1.5 crore. Review retirement corpus progress against the 25x rule. Shift allocation to 60 percent equity, 30 percent debt, 10 percent gold. Pay off all non-home-loan debt. Target becoming home loan free by 50. Target net worth of 7x annual income by age 45. This is the last decade where compounding works strongly in your favor.

50s - Consolidation Phase (Age 50-60): Retirement is now visible. Target becoming completely debt-free including home loan. Shift allocation to 40 to 50 percent equity, 40 to 50 percent debt, 10 percent gold. Maximize EPF, PPF, and NPS contributions. Calculate exact retirement corpus needed and assess the gap. If behind target, consider working 2 to 3 years longer or reducing planned retirement expenses. Review all insurance policies - ensure health cover is adequate (₹25L to ₹50L with super top-up). Start practicing living on your projected retirement budget. Target net worth of 15 to 20x annual income by retirement.

60 Plus - Retirement Phase: Switch focus from wealth accumulation to income generation and capital preservation. Implement the bucket strategy - 3 years of expenses in liquid instruments, 7 years in balanced funds, remainder in equity for growth. Set up a Systematic Withdrawal Plan from mutual funds for monthly income. Invest in SCSS (₹30L limit at 8.2 percent quarterly payout) and POMIS (₹9L limit at 7.4 percent monthly payout) for guaranteed income. Maintain 30 to 40 percent equity allocation to beat inflation over a 25 to 30 year retirement. Create or update estate plan - will, power of attorney, nominations, and communicate financial details to family. Budget ₹50,000 to ₹1,00,000/month for healthcare as you age. Enjoy the fruits of decades of disciplined saving.
`;
