export const RETIREMENT_KB = `
RETIREMENT PLANNING KNOWLEDGE BASE

The 4 Percent Rule: A widely referenced guideline stating that you can withdraw 4 percent of your retirement corpus in the first year and adjust for inflation each subsequent year, with a high probability the money will last 30 years. For India, a more conservative 3 to 3.5 percent withdrawal rate is recommended due to higher inflation (6-7 percent average). If your annual expenses are ₹6,00,000, at a 3.5 percent withdrawal rate you need a corpus of approximately ₹1.71 crore. This is a starting estimate - your actual needs depend on healthcare costs, lifestyle, and legacy goals.

The 25x Rule: A quick shortcut - multiply your expected annual retirement expenses by 25 to estimate the required corpus. If you expect to spend ₹8,00,000 per year in retirement (in today's money), you need ₹2 crore. Adjust for inflation to find the future value. At 6 percent inflation, ₹8L in today's money becomes ₹25.7L in 20 years, requiring a corpus of ₹6.4 crore. This is why starting early is non-negotiable for retirement planning.

FIRE Movement: Financial Independence, Retire Early targets accumulating 25 to 33 times annual expenses to retire well before 60. Lean FIRE means retiring with a frugal lifestyle (₹3-5L annual expenses). Fat FIRE means maintaining a comfortable lifestyle (₹15-25L annual expenses). Barista FIRE means reaching partial financial independence and working a lower-stress job for remaining expenses. Indian FIRE is more achievable due to lower cost of living, but requires accounting for higher inflation, healthcare costs, and lack of social security.

Retirement Corpus Calculation: Step 1 - estimate current monthly expenses excluding EMIs that will end before retirement. Step 2 - inflate them to retirement age at 6 to 7 percent per year. Step 3 - multiply annual inflation-adjusted expenses by 25 to 33. Example: current expenses ₹50,000/month, retirement in 25 years, inflation at 6 percent. Future monthly expenses: ₹50,000 times (1.06)^25 = ₹2,14,500/month or ₹25.7L/year. Required corpus at 25x = ₹6.4 crore. Required monthly SIP at 12 percent returns for 25 years = approximately ₹34,000.

Bucket Strategy: Divide your retirement corpus into three buckets. Bucket 1 (1-3 years of expenses) in liquid funds, FDs, and savings accounts - this covers immediate income needs and protects against sequence of returns risk. Bucket 2 (4-10 years of expenses) in balanced or hybrid funds, short-term debt funds, and bonds for moderate growth with stability. Bucket 3 (remaining corpus) in equity index funds and ELSS for long-term growth to beat inflation. Refill Bucket 1 annually from Bucket 2, and Bucket 2 from Bucket 3 during bull markets.

EPF for Retirement: Employee Provident Fund is the backbone of retirement savings for salaried Indians. Employee contributes 12 percent of basic salary, employer matches with 3.67 percent going to EPF and 8.33 percent to EPS (pension). Current interest rate is 8.25 percent, tax-free if held to retirement. Do not withdraw EPF when changing jobs - transfer it via the EPFO portal. A ₹30,000 basic salary contributing to EPF for 30 years at 8.25 percent accumulates approximately ₹1.1 crore from employee contribution alone.

NPS for Retirement: National Pension System offers Tier 1 (retirement, locked until 60) and Tier 2 (flexible, no tax benefit). At age 60, you can withdraw 60 percent as a lump sum (tax-free) and must use 40 percent to buy an annuity. NPS allows allocation to equity (up to 75 percent until age 50, then tapering), corporate bonds, and government securities. Additional ₹50,000 deduction under Section 80CCD(1B) beyond the ₹1.5L 80C limit. NPS has the lowest fund management charges in India at 0.01 to 0.09 percent.

Annuity vs SWP: An annuity provides guaranteed lifetime income but typically offers low returns (5-6 percent) with no inflation adjustment and the principal is lost on death (unless joint-life or return-of-purchase-price option chosen). A Systematic Withdrawal Plan from a mutual fund offers higher potential returns, inflation adjustment, and principal preservation, but carries market risk. Consider using annuity for essential expenses (50-60 percent of needs) and SWP for discretionary spending.

Retirement Age Planning: Retiring at 60 with a life expectancy of 85 means planning for 25 years of income. Early retirement at 45 means planning for 40 years. Healthcare costs increase exponentially after 60 - budget ₹50,000 to ₹1,00,000 per month for a couple in their 70s. Maintain health insurance coverage until at least 80. Factor in potential long-term care costs. The longer the retirement period, the more equity exposure you need to beat inflation.

Inflation Impact on Retirement: At 6 percent inflation, prices double every 12 years. A comfortable retirement requiring ₹50,000/month today will need ₹1,60,000/month in 20 years and ₹5,15,000/month in 40 years. This is why keeping your entire retirement corpus in fixed deposits at 7 percent gives only 1 percent real return (after inflation). A significant equity allocation (30-50 percent even in retirement) is essential to maintain purchasing power. Pension plans offering fixed ₹20,000/month may feel adequate today but will cover only basic groceries in 25 years.
`;
