export const RISK_MANAGEMENT_KB = `
RISK MANAGEMENT KNOWLEDGE BASE

Term Life Insurance: Pure protection without any investment component. A 30-year-old non-smoking male can get ₹1 crore coverage for approximately ₹8,000 to ₹12,000 per year. This is 10 to 20 times cheaper than endowment or ULIP plans offering the same cover. Buy term insurance equal to 10 to 15 times your annual income, or use the Human Life Value method for a more precise calculation. Popular options include HDFC Click2Protect, ICICI iProtect Smart, and LIC Tech Term. Buy as early as possible - premiums increase significantly with age.

Health Insurance: Essential for every Indian regardless of employer coverage. A family floater plan covering self, spouse, and two children with ₹10L to ₹20L sum insured costs approximately ₹15,000 to ₹30,000 per year. Add a super top-up of ₹50L to ₹1 crore for an additional ₹3,000 to ₹8,000 per year. Employer health insurance ends when you leave the job. Always maintain personal health insurance. Look for plans with no co-payment, no room rent capping, wide hospital network, and restoration benefit. Consider ₹5L to ₹10L base plan plus ₹50L super top-up as a cost-effective structure.

Human Life Value (HLV) Method: Calculate the insurance cover you need by estimating the present value of your future income minus your personal expenses. Formula: annual income minus personal expenses, multiplied by remaining working years, adjusted for inflation and investment returns. Simplified approach: if you earn ₹12L per year, spend ₹3L on yourself, have 25 working years left, your HLV at a 6 percent discount rate is approximately ₹1.15 crore. Add outstanding loans (home loan, car loan) and future obligations (children's education, marriage) to arrive at total required coverage.

Adequate Coverage: Most Indians are underinsured. The average life insurance cover in India is only ₹3 to ₹5 lakh - barely enough for a few months of family expenses. Adequate term cover should replace your income for 15 to 20 years so your family can maintain their lifestyle, pay off loans, and fund children's education. A person earning ₹15L per year with a ₹40L home loan and two young children needs at least ₹2 to ₹2.5 crore in term cover. Review coverage every 3 to 5 years and after major life events - marriage, child birth, home purchase.

Nominee and Claim Rules: In India, a nominee is merely a custodian of the insurance payout, not necessarily the legal heir. To avoid claim disputes, make a clear will specifying the intended beneficiaries. For married individuals, nominate your spouse and mention the benefit split in your will. Update nominees after every life event. For claims, notify the insurer within the specified period (usually 3 to 6 months for death claims). Keep policy documents, premium receipts, and nominee details accessible to your family. A claim cannot be rejected after 3 years from policy issuance under Section 45 of the Insurance Act.

Insurance Claim Process: For health insurance, prefer cashless claims at network hospitals - call the insurer's TPA before admission. For planned hospitalization, raise a pre-authorization request 3 to 4 days in advance. Keep all original bills, prescriptions, and discharge summaries. For reimbursement claims, submit within 15 to 30 days of discharge. For term insurance death claims, the nominee must submit the death certificate, policy document, claimant's statement, and identity proof. Most claims are settled within 30 days.

Emergency Fund vs Insurance: These serve different purposes and both are essential. An emergency fund covers short-term disruptions - job loss, minor medical issues, appliance breakdowns, or unexpected travel (₹1.5L to ₹5L). Insurance covers catastrophic events - major hospitalization (₹5L to ₹50L), death of an earner (₹1 to ₹3 crore), disability, or critical illness. Never rely solely on your emergency fund for medical expenses - a single ICU stay can cost ₹5L to ₹15L and wipe out years of savings. Never rely solely on insurance for minor emergencies - insurance has deductibles, waiting periods, and claim processing delays.

Disability and Critical Illness Insurance: Often overlooked but statistically, you are more likely to be disabled during your working years than to die. A critical illness plan pays a lump sum (₹25L to ₹1 crore) on diagnosis of specified conditions like cancer, heart attack, kidney failure, or stroke. This covers treatment costs, income loss during recovery, and lifestyle modifications. Some term plans offer critical illness riders at modest additional premiums. A standalone critical illness plan of ₹50L costs approximately ₹8,000 to ₹15,000 per year for a 30-year-old.

Insurance You Do NOT Need: Avoid endowment plans, money-back policies, and ULIPs as investment-cum-insurance products - they provide inadequate cover and poor returns (4-6 percent). Avoid child plans from insurance companies - a simple term plan plus mutual fund SIP achieves better results. Avoid accident-only insurance as your primary life cover. Avoid insurance plans sold at airports or with credit cards that offer minimal coverage at high cost. The rule is simple: keep insurance and investment separate.
`;
