export const WEALTH_BUILDING_KB = `
WEALTH BUILDING KNOWLEDGE BASE

Rule of 72: A quick mental math tool to estimate how long it takes to double your money. Divide 72 by the annual rate of return. At 6 percent (savings account/FD), money doubles in 12 years. At 8 percent (PPF/debt funds), it doubles in 9 years. At 12 percent (equity mutual funds), it doubles in 6 years. At 15 percent (high-performing equity), it doubles in under 5 years. This rule vividly illustrates why even a 3 to 4 percent difference in returns is transformative over decades.

Time Value of Money: ₹1 lakh today is worth more than ₹1 lakh ten years from now because today's rupee can be invested and grown. At 12 percent returns, ₹1L today becomes ₹3.1L in 10 years. Conversely, ₹1L needed in 10 years only requires investing ₹32,200 today at 12 percent. This principle is the foundation of all financial planning - it drives the urgency to invest early and the logic behind discounting future cash flows to present value.

Power of Compounding: Albert Einstein reportedly called compound interest the eighth wonder of the world. Compounding means you earn returns on your returns, creating exponential growth over time. ₹10,000 invested monthly at 12 percent for 10 years gives ₹23.2L (₹12L invested, ₹11.2L gains). The same SIP for 20 years gives ₹99.9L (₹24L invested, ₹75.9L gains). For 30 years it becomes ₹3.53 crore (₹36L invested, ₹3.17 crore gains). Notice how gains dwarf invested capital as time increases - this is compounding at work.

Starting Early: The single most impactful financial decision. Person A invests ₹5,000/month from age 25 to 35 (10 years, ₹6L total) and then stops. Person B invests ₹5,000/month from age 35 to 60 (25 years, ₹15L total). At 12 percent returns, Person A has ₹2.8 crore at 60 while Person B has ₹95L. Person A invested less than half but ended with nearly 3x the wealth, purely because of the earlier start. Even ₹1,000/month at age 22 is more powerful than ₹10,000/month starting at 40.

Asset Allocation by Age: A general framework - in your 20s, hold 80 to 90 percent in equity (index funds, ELSS, flexi-cap) and 10 to 20 percent in debt (PPF, EPF). In your 30s, shift to 70 to 80 percent equity and 20 to 30 percent debt, adding gold (SGBs). In your 40s, move to 60 to 70 percent equity, 25 to 30 percent debt, and 5 to 10 percent gold. In your 50s, transition to 40 to 50 percent equity, 40 to 50 percent debt, and 10 percent gold. Post-retirement, maintain 30 to 40 percent equity to beat inflation, with the rest in income-generating debt instruments.

Rebalancing: Market movements cause your actual asset allocation to drift from your target. If equity has a great year, your 70/30 equity-debt split may become 80/20, increasing your risk. Rebalancing restores the original allocation by selling overweight assets and buying underweight ones. Do this annually (calendar rebalancing) or when any asset drifts more than 5 percent from the target (threshold rebalancing). Rebalancing imposes the discipline of buying low and selling high. Tax implications of rebalancing should be considered - use new contributions to rebalance when possible to avoid triggering capital gains.

Rupee Cost Averaging: When you invest a fixed amount via SIP regardless of market levels, you automatically buy more units when prices are low and fewer when prices are high. Over a full market cycle, your average purchase cost is lower than the average market price. This is powerful in volatile markets - a Nifty 50 SIP through the 2008 crash and 2020 pandemic resulted in excellent long-term returns for patient investors. The key is to never stop SIPs during market downturns.

Systematic Transfer Plan (STP): When deploying a lump sum - from a bonus, property sale, inheritance, or redemption - park it in a liquid fund earning 6 to 7 percent and set up a weekly or monthly STP into your target equity fund over 3 to 6 months. This gives you the benefit of rupee cost averaging without leaving money idle in a savings account at 3 to 4 percent. STPs also help manage the emotional challenge of deploying large amounts into equity.

Lump Sum vs SIP: Data shows lump sum investing beats SIP about two-thirds of the time because markets trend upward over long periods. However, most investors do not have lump sums - they earn monthly salaries, making SIP the natural choice. For amounts under ₹5L, invest as a lump sum if you have a 7-plus year horizon. For ₹5L to ₹25L, use a 3-month STP. For amounts above ₹25L, use a 6-month STP. The psychological comfort of gradual deployment helps investors stay committed.
`;
